version: '3.8'

services:
  ghost:
    image: ghost:latest
    ports:
      - 2368:2368
    environment:
      url: http://localhost:2368
      NODE_ENV: 'development'
    volumes:
      - ./content/themes/:/var/lib/ghost/content/themes/
  webpack:
    image: node:14
    working_dir: /usr/src/app
    command: bash -c "npm run dev"
    ports:
      - 3000:3000
    volumes:
      - './content/themes/candidus:/usr/src/app'
  sync: 
    image: node:20
    working_dir: /usr/src/app
    env_file:
      - sync-helper/.env
    depends_on:
      - ghost
    command: bash -c "npm run sync:dev"
    volumes:
      - './sync-helper:/usr/src/app'
