name: Build latest version on push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    outputs:
      version: ${{ steps.autotag.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Auto tag
        id: autotag
        uses: butlerlogic/action-autotag@1.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          strategy: package
          root: content/themes/candidus

      - name: Build ZIP file
        run: |
          cd content/themes/candidus
          npm install
          npm run build
          mkdir dist
          zip -r dist/candidus.zip . -x "node_modules/*" -x "dist/*" -x "src/*" -x "tsconfig.json" -x "webpack.config.js" -x "zip.sh" -x "test/*" -x .env

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v3
        with:
          name: candidus-theme
          path: content/themes/candidus/dist/candidus.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Download ZIP artifact
        uses: actions/download-artifact@v3
        with:
          name: candidus-theme
          path: dist

      - name: Release as latest
        uses: svenstaro/upload-release-action@v2
        with:
          release_name: "Latest"
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/candidus.zip
          tag: latest
          overwrite: true
          file_glob: true
          make_latest: false

      - name: Release as version
        uses: svenstaro/upload-release-action@v2
        with:
          release_name: "Version ${{ needs.build.outputs.version }}"
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/candidus.zip
          tag: ${{ needs.build.outputs.version }}
          overwrite: true
          file_glob: true
          make_latest: false
